#!/bin/sh
### BEGIN INIT INFO
# Provides: noip2
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time
# Description: Enable service provided by daemon.
### END INIT INFO
case "$1" in
start)
echo "Starting No-IP"
/usr/local/etc/no-ip2.conf
;;
 
stop)
echo "Stopping No-IP"
killall noip2
;;
 
*)
echo "Usage: /etc/init.d/noip2 {start|stop}"
exit 1
;;
esac
exit 0
